export const CATEGORIES = [
  "Communication Systems",
  "Data Systems",
  "Defensive Systems",
  "Diagnostics",
  "Docking Systems",
  "Electrical Systems",
  "Emergency Systems",
  "Energy Storage",
  "Fuel Systems",
  "Hull Repair Systems",
  "Hull Systems",
  "Maintenance Tools",
  "Misc",
  "Navigation Systems",
  "Power Systems",
  "Propulsion Systems",
  "Repair Kits",
  "Sensor Systems",
  "Structural Components",
  "Thermal Systems",
];